hour = int(input("enter number of hours: "))
minute = int(input("enter number of minutes: "))
sec = int(input("enter number of seconds: "))
time_sec = ((hour*3600)+(minute*60)+(sec))
print (" time in seconds is: ",time_sec)
